-- 0009: users + PIN + role
-- ponytail: PIN (numeric 4–8 digits) hashed via node:crypto scryptSync at auth time.
-- No email, no password reset flow, no session table. Single PC, single active session,
-- role gate is a whitelist (see electron/ipc.ts). Owner-seeded with PIN 1234 — change it.

CREATE TABLE users (
  id           INTEGER PRIMARY KEY,
  name         TEXT    NOT NULL UNIQUE,
  role         TEXT    NOT NULL CHECK (role IN ('owner','counter')),
  pin_hash     TEXT    NOT NULL,   -- hex
  pin_salt     TEXT    NOT NULL,   -- hex
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX users_active_idx ON users(active, role);

-- Owner seed: pin = "1234". Hash + salt generated by the migrator on first apply
-- (SQLite has no scrypt — inserted via a follow-up INSERT OR IGNORE from ensureOwner()).
